### PR TITLE
#4500 Modifying application.yaml as required by openshift.io osio pipeline library

### PR DESCRIPTION
**Pull request by rupalibehera**
openshiftio/openshift.io#4500
This changed include the below which is required by osio pipeline library (https://github.com/fabric8io/osio-pipeline) :

1. Adds parameter - RELEASE_VERSION which is basically the
build number and will be used to differentiate between
the resources of the particular build.
2. Adds parameter - SUFFIX_NAME which is an identifier to
differentiate between the master build or other branches.
More like a master build or PR build. So whenever there is
a change in the resources of a particular branch, it applies
to the resource of that branch only. The SUFFIX_NAME variable
is used in the name of all resources.

### CODE REVIEW

**Comment by geoand** [comment]
test this please

**Comment by rupalibehera** [comment]
@geoand , could you guys have a look at this PR ?

**Comment by rupalibehera** [comment]
@Ladicek @geoand could you guys take a look at this PR we fixed the suggestion mentioned by you guys

**Comment by rupalibehera** [comment]
> @Ladicek @geoand could you guys take a look at this PR we fixed the suggestion mentioned by you guys

bump ^^

**Comment by metacosm** [comment]
@rupalibehera could you actually make these changes in all the boosters, please since now we end up with some boosters with these changes and some without? Thanks in advance.

**Comment by rupalibehera** [comment]
> @rupalibehera could you actually make these changes in all the boosters, please since now we end up with some boosters with these changes and some without? Thanks in advance.

@metacosm , the 'RUNTIME_VERSION' parameter was only for springboot boosters which I removed for the three boosters. The thorntail and Vertx boosters do not have that parameter

**Comment by metacosm** [comment]
> > @rupalibehera could you actually make these changes in all the boosters, please since now we end up with some boosters with these changes and some without? Thanks in advance.
> 
> @metacosm , the 'RUNTIME_VERSION' parameter was only for springboot boosters which I removed for the three boosters. The thorntail and Vertx boosters do not have that parameter

I meant for all the Spring Boot boosters: https://github.com/snowdrop/?utf8=%E2%9C%93&q=topic%3Abooster&type=&language=

**Comment by rupalibehera** [comment]
ok @metacosm , I can do it, we should merge all other PR's that change should not block the other PR's WDYT ?

**Comment by rupalibehera** [comment]
@metacosm
I thought of making it consistent and while testing it it failed for not resolving the image and latest was working fine. But now I tested again with the RUNTIME_VERSION I am changing it back the way it was before.

**Comment by metacosm** [comment]
Rejected based on latest discussions.

**Pull request closed without merging**
