### PR TITLE
let's set the  to 250Mi so that we can deploy more apps in namespaces with low quota

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by cmoulliard** [comment]
@rawlingsj Do you need a release including this chance or does OSIO use master branch of the booster ?

**Comment by rawlingsj** [comment]
We're going to look at using a branch of the booster catalogue https://github.com/openshiftio/booster-catalog/tree/osio if that helps?

**Comment by cmoulliard** [comment]
As osio branch is equivalent to master branch from the spring boot booster point of view, you can continue to use it. I'm curious to know what is the purpose of this branch osio and why it has been created  @ALRubinger ...

**Comment by rawlingsj** [comment]
Can we merge this PR?

**Comment by maxandersen** [comment]
> As osio branch is equivalent to master branch from the spring boot booster point of view, you can continue to use it. I'm curious to know what is the purpose of this branch osio and why it has been created @ALRubinger ...

A few reasons:

1) not all boosters makes sense on OSIO and there is no good way of filtering (right now we actually have a hack in place in the wizard to only list specific hand-tested boosters)
2) there are not yet full automatic testing of boosters so that we can block updates to the catalog when things break on OSIO

**Pull request merged**
