### PR TITLE
[SB-99] Generate licenses

### PR DESCRIPTION
**Pull request by gytis**
https://issues.jboss.org/browse/SB-99

### CODE REVIEW

**Comment by cmoulliard** [comment]
As the pom.xml modification to add the maven plugins that we will use to generate the license, ... are common to all the boosters, does it make sense to add these plugins for each booster separately or to include them with a parent pom ? @gytis @metascom

**Comment by metacosm** [comment]
I think it indeed makes sense to add the plugin configuration to the parent.

**Comment by cmoulliard** [comment]
> parent

The parent pom that we use for the moment is the booster-parent BOM. To move the code to the parent, we should contact vert.x and swarm toi explain what we did and if they agree @gytis @metacosm ?

**Comment by metacosm** [comment]
> On 27 Jun 2017, at 15:26, Charles Moulliard <notifications@github.com> wrote:
> 
> parent
> 
> The parent pom that we use for the moment is the booster-parent BOM. To move the code to the parent, we should contact vert.x and swarm toi explain what we did and if they agree @gytis <https://github.com/gytis> @metacosm <https://github.com/metacosm> ?
> 
> 
It seems likely that all starters would benefit from that plugin configuration so I vote +1 on trying to get the configuration included in booster-parent POM.

**Comment by gytis** [comment]
I agree on moving config to the parent pom. However, until that is agreed by other runtimes I think it would be good to have them in separate boosters. Just in case we won't agree before thursday, which is a release day.

**Comment by metacosm** [comment]
We could also have a spring boot specific parent as well that would inherit from the booster parent and define the plugin configuration until we can move it to the parent POM…

**Comment by cmoulliard** [comment]
> before thursday, which is a release day

Can you send today an email to obsidian team mailing list in order to get the positions of Swarm + Vert.x ? Can you also add jay and jiri in copy as it concerns a common task they have to manage

**Comment by gytis** [comment]
@cmoulliard first I'll check with prod if the solution is correct. Then will contact others.

**Comment by vibe13** [comment]
@gytis looking at it now, thanks for reaching!

**Comment by gytis** [comment]
@cmoulliard @vibe13 I've updated a pull request with new licenses/licenses-fix.xsd file as well as plugins in pom.xml. Now license names and URLs in licenses.xml are aligned automatically. In addition local copies of licenses are done automatically as well.
Let me know what do you think and what improvements could be done.
Once agreed I suggest to merge this PR and speak with Clement about moving plugins to parent-pom.

**Comment by gytis** [comment]
Also once plugins are moved to parent, I think we could move xsd files to .openshiftio directory.

**Comment by cmoulliard** [comment]
According to last discussions (July - 12 on obsidian-mailing list), do you want that we merge already what you did or we wait ... @gytis ?

**Comment by gytis** [comment]
No, I'll close this PR for now

**Comment by gytis** [comment]
Will try to move plugins to the parent pom

**Pull request closed without merging**
