### PR TITLE
Adding Spring Developer tools dependency

### PR DESCRIPTION
**Pull request by ibuziuk**
Spring Developer tools would allow to have features like hot deployment on osio
https://github.com/redhat-developer/rh-che/issues/254#issuecomment-335816550

Related issue - https://github.com/snowdrop/spring-boot-http-booster/issues/62

### CODE REVIEW

**Comment by ibuziuk** [comment]
@cmoulliard @gytis could you please take a look ?

**Comment by cmoulliard** [comment]
We will review and provide a decision this week when we will determine the impact of the change on the exist BOM, tests, ....

**Comment by ibuziuk** [comment]
thanks, waiting for your feedback. I'm planning to provide PR to health check example as well. However, for now it is arguable if health check sample should even be listed in the osio quickstarts - https://github.com/openshiftio/openshift.io/issues/1061#issuecomment-334765710

**Comment by cmoulliard** [comment]
Can you create a SB ticket here please ?

**Comment by ibuziuk** [comment]
@cmoulliard sure thing - https://github.com/snowdrop/spring-boot-http-booster/issues/62

**Comment by ibuziuk** [comment]
@cmoulliard any updates ?

**Comment by ibuziuk** [comment]
@cmoulliard  @gytis  @gastaldi this PR looks neglected. Could you provide some update ?

**Pull request merged**
